spring:
  banner:
    mode: off
  application:
    name: my_project.demo
  datasource:
    url: jdbc:mysql://localhost:3306/73dctt23
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: hocmysql1234
    username: root
  jpa: # quan trong có thể liên kết tới database
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  signerKey: GK5inCtEIvqeI1dg0YETKkr4J9e5p+EAs0rR+QlmYdnvNHIkbtqOP0rdmFYFjF9l
  valid-duration: 3600
  refreshable-duration: 7200
